name: ListRepos

on:
  workflow_dispatch:

jobs:
  listrepos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Search for repos in org
        uses: octokit/request-action@v2.x
        id: repo_list
        with:
          route: GET /search/repositories?q=org%3Ablueabraham+wash
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAT}}        

      # Runs a set of commands using the runners shell
      - name: List results from search
        run: "echo repos matched: ${{ steps.repo_list.outputs }}"
