name: ListRepos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Repos
        uses: octokit/request-action@v2.x
        id: repo_list
        with:
          route: GET /search/repositories?q=wash&org=blueabraham
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}        

      # Runs a set of commands using the runners shell
      - name: List results from search
        run: "echo repos matched: ${{ steps.repo_list.outputs.data }}"
